import { Department, AssetCategory, Employee, Asset, ResourceBooking, MaintenanceRequest, AuditCycle, AuditItem } from './types';

export const SEED_DEPARTMENTS: Department[] = [
  {
    id: 'dept-it',
    name: 'Information Technology',
    code: 'IT',
    headEmployeeId: 'emp-marcus',
    parentDepartmentId: null,
    status: 'Active',
  },
  {
    id: 'dept-ops',
    name: 'Operations & Facilities',
    code: 'OPS',
    headEmployeeId: 'emp-jack',
    parentDepartmentId: null,
    status: 'Active',
  },
  {
    id: 'dept-mkt',
    name: 'Creative Marketing',
    code: 'MKT',
    headEmployeeId: 'emp-sarah',
    parentDepartmentId: null,
    status: 'Active',
  },
  {
    id: 'dept-hr',
    name: 'Human Resources',
    code: 'HR',
    headEmployeeId: null,
    parentDepartmentId: null,
    status: 'Active',
  },
];

export const SEED_CATEGORIES: AssetCategory[] = [
  {
    id: 'cat-electronics',
    name: 'Laptops & Workstations',
    customFields: [
      { name: 'Warranty Period (Months)', type: 'number', required: true },
      { name: 'Processor', type: 'text', required: false },
    ],
    status: 'Active',
  },
  {
    id: 'cat-av',
    name: 'AV Equipment',
    customFields: [
      { name: 'Max Continuous Use Hours', type: 'number', required: false },
    ],
    status: 'Active',
  },
  {
    id: 'cat-vehicles',
    name: 'Vehicles',
    customFields: [
      { name: 'License Plate', type: 'text', required: true },
      { name: 'Odometer at Acquisition', type: 'number', required: true },
    ],
    status: 'Active',
  },
  {
    id: 'cat-furniture',
    name: 'Office Furniture',
    customFields: [
      { name: 'Assembly Required', type: 'text', required: false },
    ],
    status: 'Active',
  },
  {
    id: 'cat-rooms',
    name: 'Shared Rooms & Venues',
    customFields: [
      { name: 'Maximum Capacity', type: 'number', required: true },
    ],
    status: 'Active',
  },
];

export const SEED_EMPLOYEES: Employee[] = [
  {
    id: 'emp-sarah',
    name: 'Kshitij Patil (Admin)',
    email: 'admin@assetflow.com',
    departmentId: 'dept-mkt',
    role: 'Admin',
    status: 'Active',
    createdAt: '2026-01-10T09:00:00Z',
  },
  {
    id: 'emp-jack',
    name: 'Garvit Sharma (Manager)',
    email: 'manager@assetflow.com',
    departmentId: 'dept-ops',
    role: 'Asset Manager',
    status: 'Active',
    createdAt: '2026-01-15T10:00:00Z',
  },
  {
    id: 'emp-marcus',
    name: 'Rohan Gupta (Dept Head)',
    email: 'head@assetflow.com',
    departmentId: 'dept-it',
    role: 'Department Head',
    status: 'Active',
    createdAt: '2026-01-18T11:00:00Z',
  },
  {
    id: 'emp-jane',
    name: 'Priya Patel (Employee)',
    email: 'employee@assetflow.com',
    departmentId: 'dept-it',
    role: 'Employee',
    status: 'Active',
    createdAt: '2026-02-01T08:30:00Z',
  },
  {
    id: 'emp-bob',
    name: 'Amit Singh (Employee)',
    email: 'bob@assetflow.com',
    departmentId: 'dept-ops',
    role: 'Employee',
    status: 'Active',
    createdAt: '2026-02-15T14:00:00Z',
  }
];

export const SEED_ASSETS: Asset[] = [
  {
    id: 'asset-1',
    name: 'MacBook Pro 16" M3 Max',
    categoryId: 'cat-electronics',
    assetTag: 'AF-0001',
    serialNumber: 'C02F8XYZQ05D',
    acquisitionDate: '2026-01-20',
    acquisitionCost: 3499,
    condition: 'New',
    location: 'IT Storage Lab',
    photoUrls: [],
    documentUrls: [],
    isBookable: false,
    status: 'Allocated',
    customFieldValues: {
      'Warranty Period (Months)': 36,
      'Processor': 'Apple M3 Max',
    },
  },
  {
    id: 'asset-2',
    name: 'Dell XPS Desktop Tower',
    categoryId: 'cat-electronics',
    assetTag: 'AF-0002',
    serialNumber: 'DELL-98765-XPS',
    acquisitionDate: '2026-01-22',
    acquisitionCost: 1899,
    condition: 'Good',
    location: 'Development Bay 4',
    photoUrls: [],
    documentUrls: [],
    isBookable: false,
    status: 'Allocated',
    customFieldValues: {
      'Warranty Period (Months)': 24,
      'Processor': 'Intel Core i9',
    },
  },
  {
    id: 'asset-3',
    name: 'Sony Alpha A7 IV Camera',
    categoryId: 'cat-av',
    assetTag: 'AF-0003',
    serialNumber: 'SONY-7731298',
    acquisitionDate: '2026-02-10',
    acquisitionCost: 2499,
    condition: 'Good',
    location: 'Media Studio A',
    photoUrls: [],
    documentUrls: [],
    isBookable: true,
    status: 'Available',
    customFieldValues: {
      'Max Continuous Use Hours': 4,
    },
  },
  {
    id: 'asset-4',
    name: 'Main Boardroom Conference Table',
    categoryId: 'cat-furniture',
    assetTag: 'AF-0004',
    serialNumber: 'HM-FURN-8822',
    acquisitionDate: '2026-01-05',
    acquisitionCost: 4500,
    condition: 'Good',
    location: 'Conference Room 3A',
    photoUrls: [],
    documentUrls: [],
    isBookable: false,
    status: 'Available',
    customFieldValues: {
      'Assembly Required': 'No',
    },
  },
  {
    id: 'asset-5',
    name: 'Conference Room 3A (12-Person)',
    categoryId: 'cat-rooms',
    assetTag: 'AF-0005',
    serialNumber: 'ROOM-3A',
    acquisitionDate: '2026-01-01',
    acquisitionCost: 0,
    condition: 'Good',
    location: 'HQ Floor 3',
    photoUrls: [],
    documentUrls: [],
    isBookable: true,
    status: 'Available',
    customFieldValues: {
      'Maximum Capacity': 12,
    },
  },
  {
    id: 'asset-6',
    name: 'Ford Transit Delivery Van',
    categoryId: 'cat-vehicles',
    assetTag: 'AF-0006',
    serialNumber: 'FORD-TRANSIT-2026',
    acquisitionDate: '2026-01-15',
    acquisitionCost: 42000,
    condition: 'Fair',
    location: 'Basement Parking Spot B10',
    photoUrls: [],
    documentUrls: [],
    isBookable: true,
    status: 'Under Maintenance',
    customFieldValues: {
      'License Plate': 'TX-88A-991',
      'Odometer at Acquisition': 12000,
    },
  },
  {
    id: 'asset-7',
    name: 'Herman Miller Aeron Chair',
    categoryId: 'cat-furniture',
    assetTag: 'AF-0007',
    serialNumber: 'HM-AERON-10292',
    acquisitionDate: '2026-02-12',
    acquisitionCost: 1400,
    condition: 'Good',
    location: 'Executive Office 1',
    photoUrls: [],
    documentUrls: [],
    isBookable: false,
    status: 'Allocated',
    customFieldValues: {
      'Assembly Required': 'No',
    },
  },
  {
    id: 'asset-8',
    name: 'Epson Pro 4K Projector',
    categoryId: 'cat-av',
    assetTag: 'AF-0008',
    serialNumber: 'EPS-PR-40192',
    acquisitionDate: '2026-02-20',
    acquisitionCost: 1299,
    condition: 'Good',
    location: 'Equipment Locker C',
    photoUrls: [],
    documentUrls: [],
    isBookable: true,
    status: 'Available',
    customFieldValues: {
      'Max Continuous Use Hours': 8,
    },
  },
  {
    id: 'asset-9',
    name: 'Creative Studio Suite B',
    categoryId: 'cat-rooms',
    assetTag: 'AF-0009',
    serialNumber: 'ROOM-SUITE-B',
    acquisitionDate: '2026-01-01',
    acquisitionCost: 0,
    condition: 'Good',
    location: 'HQ Floor 2',
    photoUrls: [],
    documentUrls: [],
    isBookable: true,
    status: 'Available',
    customFieldValues: {
      'Maximum Capacity': 8,
    },
  },
  {
    id: 'asset-10',
    name: 'Toyota Prius (Hybrid Electric)',
    categoryId: 'cat-vehicles',
    assetTag: 'AF-0010',
    serialNumber: 'TOY-PRI-77112',
    acquisitionDate: '2026-03-01',
    acquisitionCost: 28500,
    condition: 'New',
    location: 'Basement Parking Spot B11',
    photoUrls: [],
    documentUrls: [],
    isBookable: true,
    status: 'Available',
    customFieldValues: {
      'License Plate': 'TX-11B-332',
      'Odometer at Acquisition': 15,
    },
  },
  {
    id: 'asset-11',
    name: 'Samsung Galaxy Tab S9 Ultra',
    categoryId: 'cat-electronics',
    assetTag: 'AF-0011',
    serialNumber: 'SAMP-91928-TAB',
    acquisitionDate: '2026-03-10',
    acquisitionCost: 1099,
    condition: 'Good',
    location: 'IT Storage Lab',
    photoUrls: [],
    documentUrls: [],
    isBookable: false,
    status: 'Available',
    customFieldValues: {
      'Warranty Period (Months)': 12,
      'Processor': 'Snapdragon Gen 2',
    },
  },
  {
    id: 'asset-12',
    name: 'L-Shaped Standing Desk',
    categoryId: 'cat-furniture',
    assetTag: 'AF-0012',
    serialNumber: 'STAND-FURN-310',
    acquisitionDate: '2026-02-18',
    acquisitionCost: 650,
    condition: 'Good',
    location: 'Dev Room C',
    photoUrls: [],
    documentUrls: [],
    isBookable: false,
    status: 'Retired',
    customFieldValues: {
      'Assembly Required': 'Yes',
    },
  },
  {
    id: 'asset-13',
    name: 'Bose Noise Cancelling Headphones',
    categoryId: 'cat-av',
    assetTag: 'AF-0013',
    serialNumber: 'BOSE-QC-45',
    acquisitionDate: '2026-02-22',
    acquisitionCost: 329,
    condition: 'Good',
    location: 'Equipment Locker A',
    photoUrls: [],
    documentUrls: [],
    isBookable: false,
    status: 'Allocated',
    customFieldValues: {
      'Max Continuous Use Hours': 20,
    },
  }
];

export const SEED_ALLOCATIONS = [
  {
    id: 'alloc-1',
    assetId: 'asset-1',
    employeeId: 'emp-jane',
    departmentId: null,
    allocatedDate: '2026-02-05',
    expectedReturnDate: '2026-08-05',
    actualReturnDate: null,
    status: 'Active' as const,
    conditionCheckInNotes: null,
    history: [],
  },
  {
    id: 'alloc-2',
    assetId: 'asset-2',
    employeeId: null,
    departmentId: 'dept-it',
    allocatedDate: '2026-01-25',
    expectedReturnDate: null,
    actualReturnDate: null,
    status: 'Active' as const,
    conditionCheckInNotes: null,
    history: [],
  },
  {
    id: 'alloc-3',
    assetId: 'asset-7',
    employeeId: 'emp-marcus',
    departmentId: null,
    allocatedDate: '2026-02-15',
    expectedReturnDate: '2026-06-15', // Past expected return date!
    actualReturnDate: null,
    status: 'Overdue' as const, // We seed it as Overdue!
    conditionCheckInNotes: null,
    history: [],
  },
  {
    id: 'alloc-4',
    assetId: 'asset-13',
    employeeId: 'emp-bob',
    departmentId: null,
    allocatedDate: '2026-02-25',
    expectedReturnDate: '2026-03-25', // Past expected return date!
    actualReturnDate: null,
    status: 'Overdue' as const, // Overdue allocation
    conditionCheckInNotes: null,
    history: [],
  }
];

export const SEED_BOOKINGS: ResourceBooking[] = [
  {
    id: 'book-1',
    resourceAssetId: 'asset-5',
    bookedBy: 'emp-jane',
    departmentId: 'dept-it',
    startTime: '2026-07-12T09:00:00',
    endTime: '2026-07-12T10:30:00',
    status: 'Upcoming',
  },
  {
    id: 'book-2',
    resourceAssetId: 'asset-5',
    bookedBy: 'emp-marcus',
    departmentId: 'dept-it',
    startTime: '2026-07-12T11:00:00',
    endTime: '2026-07-12T12:00:00',
    status: 'Upcoming',
  },
  {
    id: 'book-3',
    resourceAssetId: 'asset-3',
    bookedBy: 'emp-bob',
    departmentId: 'dept-ops',
    startTime: '2026-07-11T14:00:00',
    endTime: '2026-07-11T17:00:00',
    status: 'Completed',
  }
];

export const SEED_MAINTENANCE: MaintenanceRequest[] = [
  {
    id: 'maint-1',
    assetId: 'asset-6',
    raisedBy: 'emp-bob',
    issueDescription: 'Engine check light is blinking and cabin air filter needs replacement.',
    priority: 'High',
    photoUrl: null,
    status: 'Technician Assigned',
    technicianName: 'Master Repair Services Inc.',
  },
  {
    id: 'maint-2',
    assetId: 'asset-3',
    raisedBy: 'emp-sarah',
    issueDescription: 'Lens mount sensor contact pins are occasionally unresponsive.',
    priority: 'Medium',
    photoUrl: null,
    status: 'Pending',
  }
];

export const SEED_AUDITS: AuditCycle[] = [
  {
    id: 'audit-1',
    scopeDepartmentId: 'dept-it',
    scopeLocation: null,
    dateRangeStart: '2026-07-01',
    dateRangeEnd: '2026-07-15',
    auditorIds: ['emp-jack'],
    status: 'Open',
  }
];

export const SEED_AUDIT_ITEMS: AuditItem[] = [
  {
    id: 'audit-item-1',
    auditCycleId: 'audit-1',
    assetId: 'asset-1',
    verdict: 'Verified',
    notes: 'In perfect working condition, held by Priya Patel.',
  }
];
